name: midi_location
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # ... daftar dependencies Anda yang lain ...
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  fl_chart: ^0.71.0
  google_fonts: ^6.2.1
  go_router: ^16.2.1
  http: ^1.5.0
  dropdown_search: ^6.0.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^17.2.1
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  flutter_launcher_icons: ^0.13.1
  mime: ^1.0.4 
  equatable: ^2.0.5
  file_picker: ^8.0.0
  path_provider: ^2.1.3
  dropdown_button2: ^2.3.9
  url_launcher: ^6.3.2
  month_picker_dialog: ^6.5.0
  uuid: ^4.4.0
  open_filex: ^4.7.0
  pinput: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/pic/midiloc.png"

# PERBAIKAN DI SINI: Indentasi sudah benar
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/pic/midiloc.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

  # Atur tampilan splash di Android 12+
  android_12:
    image: assets/pic/midiloc.png
    color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons/home.svg
    - assets/icons/location.svg
    - assets/icons/map.svg
    - assets/icons/profile.svg
    - assets/icons/addulok.svg
    - assets/icons/edit_profile.svg
    - assets/icons/email.svg
    - assets/icons/phone.svg
    - assets/icons/help.svg
    - assets/icons/about.svg
    - assets/icons/right_arrow.svg
    - assets/icons/left_arrow.svg
    - assets/icons/avatar.svg
    - assets/icons/notification.svg
    - assets/icons/logo_midi.png
    - assets/icons/data_store.svg
    - assets/icons/indonesia.svg
    - assets/icons/down_arrow.svg
    - assets/icons/calender.svg
    - assets/icons/error.svg
    - assets/pic/topbarlogo.png
    - assets/icons/notifikasi.svg
    - assets/pic/alfamidilogohd.png
    - assets/icons/editulok.svg
    - assets/pic/alfamididown.png
    - assets/pic/alfamidilogohd.png
    - assets/pic/topbarlogo.png
    - assets/icons/404.svg
    - assets/icons/access_denied.svg
    - assets/icons/no_connection.svg
    - assets/icons/under_maintenance.svg
    - assets/icons/time.svg
    - assets/pic/bg_2.png
    - assets/pic/midiloc.png
    - assets/icons/analisis.svg
    - assets/icons/draft.svg
    - assets/icons/lampiran.svg
    - assets/icons/upload.svg
    - assets/icons/success.svg
    - assets/icons/locations.svg
    - assets/icons/maps.svg
    - assets/icons/nok.svg
    - assets/icons/ok.svg
    - assets/icons/in_progress.svg

